### ISSUE TITLE
[Enhancement]关于 DRI3

### ISSUE THREAD

**Issue by Mr-Metatron** [Cateners/tiny_computer#106]
不知道开发者有没有看到过这个 issue 呢？https://github.com/xDoge26/proot-setup/issues/26
这个 issue 里面好像解决了 DRI3 不能用的问题

**Comment by Cateners** [comment]
那是因为termux x11有dri3的支持，但vnc我好像没看到过，我自己也不会

**Comment by Mr-Metatron** [comment]
> 那是因为termux x11有dri3的支持，但vnc我好像没看到过，我自己也不会

好的，谢谢解答
