### ISSUE TITLE
WPS安装错误404什么的

### ISSUE THREAD

**Issue by panliuanm** [Cateners/tiny_computer#110]
@Cateners 能修复吗？

**Comment by panliuanm** [comment]
![S40910-09471610.png](https://github.com/user-attachments/assets/06cef053-7dab-4574-b8c2-5a6a8d44681a)

**Comment by tianmingwan** [comment]
网页删了，网上自己找wps arm64 deb安装包用sudo apt install装

**Comment by panliuanm** [comment]
> 网页删了，网上自己找wps arm64 deb安装包用sudo apt install装

怎么找我找不到

**Comment by tianmingwan** [comment]
直接百度搜linux arm64 wps包 csdn上面有免费的

**Comment by Cateners** [comment]
https://github.com/Cateners/tiny_computer/issues/98
