### ISSUE TITLE
谁知道怎么把proot变成chroot，我已经获得手机root权限了

### ISSUE THREAD

**Issue by sfkdgyz** [Cateners/tiny_computer#114]
来个大佬教教吧，求求了

**Comment by sfkdgyz** [comment]
或者说怎么给小小电脑root权限，我magisk里已经给了，但是似乎没啥用

**Comment by Cateners** [comment]
proot变chroot没有什么必要还麻烦。我反正不打算做这个
教程的话，你可以看下tmoe大佬的解释：https://gitee.com/mo2/linux/issues/I5HET8
