### ISSUE TITLE
怎么给小小电脑root权限啊，我已经获得了ROOT权限了

### ISSUE THREAD

**Issue by sfkdgyz** [Cateners/tiny_computer#115]
用magisk给小小电脑权限，但依然无法访问etc之类的文件，导致我无法配置IP

**Comment by NeverYouGetYouUp001** [comment]
你主动给小小电脑的还是小小电脑说要root权限的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月15日(周日) 上午10:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Cateners/tiny_computer] 怎么给小小电脑root权限啊，我已经获得了ROOT权限了 (Issue #115)




 
用magisk给小小电脑权限，但依然无法访问etc之类的文件，导致我无法配置IP
