### ISSUE TITLE
`no sandbox is not supported`怎么解

### ISSUE THREAD

**Issue by zhengzepeng** [Cateners/tiny_computer#120]
安装chromium启动的时候报错，`no sandbox is not supported`，一些类似于基于chromium的应用（electron），诸如洛雪等都打开不了，有什么方式能解决？

**Comment by Cateners** [comment]
它说的是no sandbox is not supported？还是without --no-sandbox is not supported？后者的话在启动命令添加一个--no-sandbox即可

**Comment by zhengzepeng** [comment]
> 它说的是no sandbox is not supported？还是without --no-sandbox is not supported？后者的话在启动命令添加一个--no-sandbox即可

可以了，加上`--no-sandbox`就可以运行了，多谢多谢
