### ISSUE TITLE
WPS安装不了

### ISSUE THREAD

**Issue by 123zzamm** [Cateners/tiny_computer#121]
点安装WPS显示404错误![Screenshot_20240919_212808.jpg](https://github.com/user-attachments/assets/5f6589dc-968d-4ea8-9a44-49d6f200b124)

**Comment by NeverYouGetYouUp001** [comment]
见 [#98](https://github.com/Cateners/tiny_computer/issues/98) issue skividbidbdidbi

**Comment by xbmanh** [comment]
可能为了保护华为等厂商的利益
