### ISSUE TITLE
能否在虚拟按键那一栏添加自定义快捷键

### ISSUE THREAD

**Issue by haozhuren** [Cateners/tiny_computer#136]
作者您好，目前的虚拟键盘那一栏有一些如ctrl，alt之类的修饰键，请问有没有办法自定义一些组合按键，比如复制粘贴等？termux有相关的修改方案，不知道这个app有没有相关的修改方案？

**Comment by Cateners** [comment]
我约等于直接用了Terminal Studio的终端，至于它怎么处理的没有详细看过🥹

**Comment by haozhuren** [comment]
> 我约等于直接用了Terminal Studio的终端，至于它怎么处理的没有详细看过🥹

感谢回复！但是我似乎并没有找到.termux这个文件夹诶

**Comment by Cateners** [comment]
是这个Terminal Studio，不是Termux：https://github.com/TerminalStudio

**Comment by haozhuren** [comment]
> 是这个Terminal Studio，不是Termux：https://github.com/TerminalStudio

好的，谢谢，我用termux11实现这个效果了
