### ISSUE TITLE
分辨率与刷新率

### ISSUE THREAD

**Issue by PLAYERiv65** [Cateners/tiny_computer#14]
我无法自由地自定义分辨率与刷新率，远程调整大小可以调整分辨率但无法同时调整分辨率和缩放，本地缩放则会导致显示错误。高分辨率适配只是简单提高了分辨率，并没有解决不能自由自定义的问题。

**Comment by Cateners** [comment]
在开启本地缩放的情况下，前往小小电脑系统的显示设置调整试试？🤔
