### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by jiushier** [Cateners/tiny_computer#149]
大神，能添加一个清理缓存和删除无用库的快捷操作吗？

**Comment by Cateners** [comment]
新版添加了清除包管理器缓存的指令。另外，检查更新的快捷指令有删除无用库的功能。

**Comment by jiushier** [comment]
大神




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月10日(星期天) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Cateners/tiny_computer] 一点建议 (Issue #149)














 
新版添加了清除包管理器缓存的指令。另外，检查更新的快捷指令有删除无用库的功能。
