### ISSUE TITLE
关于turnip+Zink问题

### ISSUE THREAD

**Issue by Cinght520** [Cateners/tiny_computer#155]
使用turnip+Zink后发现窗口标题栏和任务栏都消失不见，右键桌面选择桌面窗口微调打不开，我推测可能是开启以后导致桌面窗口无法启动，并且鼠标也是黑色的，我希望他能继续变成windows的白色
After using turnip + Zink, I found that the title bar and taskbar of the window disappeared. I could not open the desktop window by right-clicking the desktop window. I speculated that the desktop window could not be started after it was opened, and the mouse was black. I hoped that it would continue to become the white of windows.
![Screenshot_20241110_103753_com_fct_tiny_VncActivity](https://github.com/user-attachments/assets/56778d81-c4ec-4cef-8ebb-7e506255d729)

**Comment by Cateners** [comment]
你的垂直同步开着吗？如果开了得手动关上（把文件~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml内vblank_mode值从auto改为off）

**Comment by Cinght520** [comment]
不好意思我应该怎么去操作呢？
![Screenshot_20241110_143331_com_fct_tiny_VncActivity](https://github.com/user-attachments/assets/e65789b6-efce-4538-8af5-468629b8776d)

**Comment by Cateners** [comment]
可以输nano ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml回车，找到vblank_mode那行，后面应该会有个auto，把它改成off。然后Ctrl+S保存，Ctrl+X退出。

或者直接重装下软件？因为默认就是关着的......

**Comment by Cinght520** [comment]
我是从旧版本升级过来的，经过测试，发现是旧版本中垂直同步是开着的
