### ISSUE TITLE
有点没想明白为什么要加广告

### ISSUE THREAD

**Issue by PlayMcBKuwu** [Cateners/tiny_computer#18]
- 可以理解作者需要支持，那些功能也在系统内可以解决，但是似乎不大友好
- 虽说协议是 GPL 我也没法说你加广告有问题（

**Comment by Cateners** [comment]
要去广告的话，workflow代码里有个vip变量，把它改成1应该就行。

emm这个软件大概在九月初开始做的吧，我从毕业到现在都没找到工作，如果有收入来源自然是好的。还有一个原因是以前没在应用里加过广告，所以想试试！

但是好像国内的广告商都不对个人开发者提供服务的样子。谷歌广告国内大概率用不了，所以用了Unity广告。其实到现在广告费连10块人民币都没有，而且还得满100美元才能提现......还没B站发视频激励给的多（15块）。

那个Unity广告插件是MIT协议的所以兼容方面应该没什么问题......

**Comment by PlayMcBKuwu** [comment]
> 要去广告的话，workflow代码里有个vip变量，把它改成1应该就行。
> 
> emm这个软件大概在九月初开始做的吧，我从毕业到现在都没找到工作，如果有收入来源自然是好的。还有一个原因是以前没在应用里加过广告，所以想试试！
> 
> 但是好像国内的广告商都不对个人开发者提供服务的样子。谷歌广告国内大概率用不了，所以用了Unity广告。其实到现在广告费连10块人民币都没有，而且还得满100美元才能提现......还没B站发视频激励给的多（15块）。
> 
> 那个Unity广告插件是MIT协议的所以兼容方面应该没什么问题......

明白了 ww

**Comment by soloopooo** [comment]
＠Cateners 顺便一提，横幅广告是有的，但大多情况下需要翻墙才能加载出来，可以把
 ‘支持作者’一栏里的介说明修改一番了（

**Comment by Cateners** [comment]
广告删了~
