### ISSUE TITLE
NT QQ 无法运行

### ISSUE THREAD

**Issue by Rechrd** [Cateners/tiny_computer#22]
无论是官网最新版还是app内置指令版本，前者打不开后者干脆找不到包![Screenshot_2024-03-06-23-08-17-12_2279741c0dede0d4ce8cbad47dbe178c.jpg](https://github.com/Cateners/tiny_computer/assets/61573442/023f2ec4-4030-4340-8685-2138da858229)

![Screenshot_2024-03-06-01-44-22-00_2279741c0dede0d4ce8cbad47dbe178c.jpg](https://github.com/Cateners/tiny_computer/assets/61573442/f0fc610f-93c0-4453-a78a-85d1b6a042fb)

**Comment by Cateners** [comment]
官网的版本加上--no-sandbox参数即可运行；
我会尽快修复指令。

**Comment by fatinghenji** [comment]
当通过官网更新qq后，无法通过点击图标启动qq，而是必须使用`--no-sandbox`。但是我看到这个issue已经标记为完毕并关闭了，请问这是一个永久性的解决办法吗？还是需要在后续的版本中修复这个问题。

**Comment by Rechrd** [comment]
加上no sandbox的确解决了，应该算一个永久的解决方案？

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: VantHoff ***@***.***&gt;
发送时间: 2024年11月30日 23:25
收件人: Cateners/tiny_computer ***@***.***&gt;
抄送: Rechrd ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Cateners/tiny_computer] NT QQ 无法运行 (Issue #22)
