### ISSUE TITLE
开启VirGL后页面文字渲染错误

### ISSUE THREAD

**Issue by K2O2** [Cateners/tiny_computer#23]
![Screenshot_20240310-013711](https://github.com/Cateners/tiny_computer/assets/88973278/53ec9fcf-2354-427c-873f-e4902d3ab927)
![Screenshot_20240310-013722](https://github.com/Cateners/tiny_computer/assets/88973278/111ff938-7412-4128-aae1-4f6853bb5192)

**Comment by Cateners** [comment]
删除virgl加速-图形环境变量里的MESA_GL_VERSION_OVERRIDE=4.0应该就可以了！
（保留这个是为了防止一些程序不能运行，现在看好像没什么必要。我之后会删掉）

**Comment by K2O2** [comment]
感謝你的郵件，文字已经可以正常渲染了，再次感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 下午5:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cateners/tiny_computer] 开启VirGL后页面文字渲染错误 (Issue #23)




 
删除virgl加速-图形环境变量里的MESA_GL_VERSION_OVERRIDE=4.0应该就可以了！
 （保留这个是为了防止一些程序不能运行，现在看好像没什么必要。我之后会删掉）
