### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Kiraprint** [Cateners/tiny_computer#24]
May you also pin instruction how to enable english localization? 
I've already tried to 'dpkg-reconfigure locales' but the system still in chinese.   

This app should be more popular but it needs the option to build system only with english (default).

**Comment by Kiraprint** [comment]
To do that need to edit "advanced" state with launch command, and write LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8.

**Comment by Cateners** [comment]
Hello, since the system is created using the tmoe tool, you can use the locale modification feature provided by tmoe (although tmoe will install unnecessary packages like proot).
Enter tmoe in terminal, select Manager, then 4-locale.
