### ISSUE TITLE
小小电脑的root密码错误

### ISSUE THREAD

**Issue by Samll-jiang** [Cateners/tiny_computer#43]
在安装某些软件时提示要安装额外的东西，但是需要root密码，输入文中展示的密码“tiny”并不正确，请问root密码是？

**Comment by Cateners** [comment]
请问是安装什么软件时出现这个问题的呢？

**Comment by Samll-jiang** [comment]
> 请问是安装什么软件时出现这个问题的呢？

steam qwq

**Comment by Cateners** [comment]
emm steam我也试过，把能修的错误都修过还是会有问题。可能是vnc的问题？据说mobox那边用termux-x11没有问题

**Comment by Samll-jiang** [comment]
啊这
