### ISSUE TITLE
文件夹里的照片不可见问题

### ISSUE THREAD

**Issue by 695422563** [Cateners/tiny_computer#46]
![Screenshot_2024-05-30-13-29-32-431_com fct tiny](https://github.com/Cateners/tiny_computer/assets/171213121/4e95b6b1-6674-4f27-8797-28e89981cdc9)
请问如何解决，还是后面版本会优化呢

**Comment by Cateners** [comment]
最新版容器（v1.0.16）安装了图片查看器。
