### ISSUE TITLE
无法下载办公软件WPS

### ISSUE THREAD

**Issue by Bubble-toru** [Cateners/tiny_computer#75]
WPS下载链接失效，其官网上无相应的安装包，是否可以安利其它的办公软件。

**Comment by Cateners** [comment]
旧版目前还可以下载，先凑合用吧😂
11720版本链接：https://wps-linux-personal.wpscdn.cn/wps/download/ep/Linux2019/11720/wps-office_11.1.0.11720_arm64.deb?k=48b0f44d4dfabdb306f84826e3edce8b&t=0x7f53d55201314

**Comment by Cateners** [comment]
在最新版（v1.0.16）固定了链接。
