### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by AJieStill** [Cateners/tiny_computer#84]
16版  wps安装失败

**Comment by Cateners** [comment]
完喽，wps被彻底下架了

**Comment by AJieStill** [comment]
啊？

**Comment by AJieStill** [comment]
> 完喽，wps被彻底下架了

那有什么其他办法吗？ 为什么我从网页下载安装包 安装不了呢

**Comment by Cateners** [comment]
wps把arm64架构的安装包下架了。你现在只能在官网下载到x64的安装包。
你可以搜一下看还有没有其他地方有arm64架构、linux版wps，下载后可以安装的

**Comment by Cateners** [comment]
可以用星火应用商店装！稳啦
![Screenshot_2024-08-09-23-36-36-984_com fct tiny](https://github.com/user-attachments/assets/e703e1ef-e54c-4bc5-b4dd-4068f8c192e4)

**Comment by AJieStill** [comment]
> 可以用星火应用商店装！稳啦
> ![Screenshot_2024-08-09-23-36-36-984_com fct tiny](https://github.com/user-attachments/assets/e703e1ef-e54c-4bc5-b4dd-4068f8c192e4)
> 

好的大佬  我试试

**Comment by CCode-xxl** [comment]
怎么安装星火商店？

**Comment by CCode-xxl** [comment]
> 可以用星火应用商店装！ 稳啦 ![Screenshot_2024-08-09-23-36-36-984_com fct tiny](https://private-user-images.githubusercontent.com/58554009/356668090-e703e1ef-e54c-4bc5-b4dd-4068f8c192e4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzA3MzUsIm5iZiI6MTcyMzI3MDQzNSwicGF0aCI6Ii81ODU1NDAwOS8zNTY2NjgwOTAtZTcwM2UxZWYtZTU0Yy00YmM1LWI0ZGQtNDA2OGY4YzE5MmU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2MTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZGExMjRmZjY0YjllNDUzYjg1MDhlZTViMmI4NDdlYTdkNTFhZTRmZDA0NTExMGRjMDEwMmRhODA5YTdmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRFFxRP2v9JfXcLyv_GYKsg0R2Ykk1-0Ejv2uhET_C0)

怎么安装星火应用商店？

**Comment by AJieStill** [comment]
> > 可以用星火应用商店装！ 稳啦 ![Screenshot_2024-08-09-23-36-36-984_com fct tiny](https://private-user-images.githubusercontent.com/58554009/356668090-e703e1ef-e54c-4bc5-b4dd-4068f8c192e4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzA3MzUsIm5iZiI6MTcyMzI3MDQzNSwicGF0aCI6Ii81ODU1NDAwOS8zNTY2NjgwOTAtZTcwM2UxZWYtZTU0Yy00YmM1LWI0ZGQtNDA2OGY4YzE5MmU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2MTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZGExMjRmZjY0YjllNDUzYjg1MDhlZTViMmI4NDdlYTdkNTFhZTRmZDA0NTExMGRjMDEwMmRhODA5YTdmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRFFxRP2v9JfXcLyv_GYKsg0R2Ykk1-0Ejv2uhET_C0)
> 
> 怎么安装星火应用商店？

直接 网上搜 下载安装包 arm版的

**Comment by hjobserver** [comment]
> > > 可以用星火应用商店装！ 稳啦 ![Screenshot_2024-08-09-23-36-36-984_com fct tiny](https://private-user-images.githubusercontent.com/58554009/356668090-e703e1ef-e54c-4bc5-b4dd-4068f8c192e4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzA3MzUsIm5iZiI6MTcyMzI3MDQzNSwicGF0aCI6Ii81ODU1NDAwOS8zNTY2NjgwOTAtZTcwM2UxZWYtZTU0Yy00YmM1LWI0ZGQtNDA2OGY4YzE5MmU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2MTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZGExMjRmZjY0YjllNDUzYjg1MDhlZTViMmI4NDdlYTdkNTFhZTRmZDA0NTExMGRjMDEwMmRhODA5YTdmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRFFxRP2v9JfXcLyv_GYKsg0R2Ykk1-0Ejv2uhET_C0)
> > 
> > 
> > 怎么安装星火应用商店？
> 
> 直接 网上搜 下载安装包 arm版的

下的是arm版本为啥打开后过一会儿闪退呢

**Comment by AJieStill** [comment]
> > > > 可以用星火应用商店装！ 稳啦 ![Screenshot_2024-08-09-23-36-36-984_com fct tiny](https://private-user-images.githubusercontent.com/58554009/356668090-e703e1ef-e54c-4bc5-b4dd-4068f8c192e4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzA3MzUsIm5iZiI6MTcyMzI3MDQzNSwicGF0aCI6Ii81ODU1NDAwOS8zNTY2NjgwOTAtZTcwM2UxZWYtZTU0Yy00YmM1LWI0ZGQtNDA2OGY4YzE5MmU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2MTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZGExMjRmZjY0YjllNDUzYjg1MDhlZTViMmI4NDdlYTdkNTFhZTRmZDA0NTExMGRjMDEwMmRhODA5YTdmM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jRFFxRP2v9JfXcLyv_GYKsg0R2Ykk1-0Ejv2uhET_C0)
> > > 
> > > 
> > > 怎么安装星火应用商店？
> > 
> > 直接 网上搜 下载安装包 arm版的
> 
> 下的是arm版本为啥打开后过一会儿闪退呢

看看这个  要不解决不了 就问一下大神
【【小教程】无需刷机！手机平板一键使用电脑版WPS以及各种电脑软件-哔哩哔哩】 https://b23.tv/t9zjC7j

**Comment by Cateners** [comment]
可以试一下最新版（v1.0.17），应该可以用了

**Comment by AJieStill** [comment]
> 可以试一下最新版（v1.0.17），应该可以用了
这个版本可以装Java吗
