### ISSUE TITLE
怎么安装星火应用商店？

### ISSUE THREAD

**Issue by CCode-xxl** [Cateners/tiny_computer#87]
怎么安装星火应用商店，之前安装完之后打开就闪退了。

**Comment by hjobserver** [comment]
更新到最新版本可以解决，但是仍然有问题，就是主界面文字不显示，推荐用星火应用商店终端版本

**Comment by liangniao09** [comment]
直接用他自带的浏览器搜星火应用商店，然后下载arm64.deb的安装包，再用自带的安装器安装就可以了
