### ISSUE TITLE
为什么看不到自己的局域网ip

### ISSUE THREAD

**Issue by sfkdgyz** [Cateners/tiny_computer#92]
下载个小皮面板但是看不到自己的局域网iP。还有就是明明获取了root权限，但是打"ip"依然显示无权限

**Comment by NeverYouGetYouUp001** [comment]
ipchonfig

**Comment by sfkdgyz** [comment]
> ipconfig

输入这个提示"未找到命令"

**Comment by NeverYouGetYouUp001** [comment]
我typo了，应该为“ifconfig” 或者 “ip addr”



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月18日(周日) 晚上7:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cateners/tiny_computer] 为什么看不到自己的局域网ip (Issue #92)




  
ipconfig
  
输入这个提示"未找到命令"

**Comment by sfkdgyz** [comment]
> 我typo了，应该为“ifconfig” 或者 “ip addr”
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月18日(周日) 晚上7:29 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Cateners/tiny_computer] 为什么看不到自己的局域网ip (Issue #92) ipconfig 输入这个提示"未找到命令" — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

输入ifconfig显示"未找到命令",输入ip addr显示"没有权限"。我已经获取了root权限，并且安装了ifconfig前置的东西，还有很多东西明明安装了但依然显示找不到命令

**Comment by Cateners** [comment]
安卓13权限所限。和 #25 是一个问题
