### ISSUE TITLE
使用作者提供的一键安装，但是wps显示安装错误，其他的安装成功打开后桌面上没有

### ISSUE THREAD

**Issue by crq8888** [Cateners/tiny_computer#98]

**Comment by Gesui0429** [comment]
wps安装我也报错，应该是官网把arm64的deb包给撤了，其他软件安装后在左下角中的所有应用程序中可以找到

**Comment by Cateners** [comment]
wps官网早就撤包了，后来我改成了山东大学镜像站的地址，就是这个https://mirrors.sdu.edu.cn/spark-store-repository/aarch64-store/office/wps-office/ ，应该是里面的wps改名了所以404，先自行下载吧

**Comment by songjiyuan** [comment]
> wps官网早就撤包了，后来我改成了山东大学镜像站的地址，就是这个https://mirrors.sdu.edu.cn/spark-store-repository/aarch64-store/office/wps-office/ ，应该是里面的wps改名了所以404，先自行下载吧

不是改了名字， 是山东大学镜像站的wps版本有升级，另外目录位置也变了，想要稳定， 最好还是自建一个gitee放这些资源

**Comment by Cateners** [comment]
最新版（v1.0.18）又修了一次，希望能撑久点
