### ISSUE TITLE
第二个小bug，安装星火商店，首页文字无法显示

### ISSUE THREAD

**Issue by huayuprophet** [Cateners/tiny_computer#99]
就是星火商店首页文字无法显示，搜索应用时的应用名称和介绍也不显示，只有点进去应用详情才能看到

**Comment by kute20140213** [comment]
火星商店的问题，又不是小小电脑的问题，你去火星商店github上说呀

**Comment by huayuprophet** [comment]
> 火星商店的问题，又不是小小电脑的问题，你去火星商店github上说呀

好像是小小电脑的问题，不过没关系，现在新版本的tinycomputer已经解决了
